<?php

namespace My\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractItemRepository extends EntityRepository
{
}
