my_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyAdminBundle:Default:index }

my_admin_contollers:
    resource: "@MyAdminBundle/Controller"
    type: annotation
    prefix: /