services:
    my_admin.twig_extension.admin_extension:
        class: My\AdminBundle\Twig\Extension\AdminExtension
        arguments: [ @service_container, @security.token_storage, @security.authorization_checker ]
        tags:
            - { name: twig.extension }
