my_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyUserBundle:Default:index }

my_user_contollers:
    resource: "@MyUserBundle/Controller"
    type: annotation
    prefix: /